# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NETCO-test-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "TinyConstraints"

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxReachability'


  # Pods for NETCO-test-app

end
